---
name: uzu-tests
language:
  - en
  - ja
themes:
  - default
  - summer2017:
      port: 4333
      exclude_pages:
        - excludeme
template_engine: mustache
url: https://gitlab.com/samcns/uzu
author: Sam Morrison
exclude:
  - bad_folder
  - bad_file.txt
pre_command: "echo 'pre-command test'"
post_command: "echo 'post-command test'"
